env:
  global:
    - secure: HfgRjXrPIva/AIOzAeNwljTSxZjFYF8s4MjbMXff9Ac7olZUE+j715RE6ayB2G4uxGFjsig4TLf1r9vv+DdwRQmkn4zNHDjC3876o2Kyuoybi9Fr87I1b94Y07V/Ft1/heQ5jHoETmpepwJBN7YMjHNbaYxyZWAZS8eZidb2rds9Bx7MPwUYglPcHAXkogO5qq1L0BVkGPmvKNjd3unkpsOFm+J6Y8BFy1eYWFCRmxLxqgdm4IjFrO+hLF/NA+FaoDbFqwfn/ZuLznzAScmlKa/ntGv8p1LENJzq92aBMatrseBp2+s2LB/+o0BlwSwBNbNhc7C5LbDHevbTiRQMbJMH/XxwvMJ2GKNBPmjAkgZMwdH5+vQHSxZy7KlWe1qvsdQyzdnsscEOz5wGgn5yMzX22bIE63Cpxx+uHZWOWjvoKL2tAPbwbXL78uxCfidcjSVzXhpQV9sN8zrPA262WyieZZyXIOArYLSILUb17SQIkpoydDgcJb9fITZaDF3wPDLRc3lx+SHqMrnOSr+ubg6XD1tDm4inZjD1UptJ2k9DqrEtXnXWJurV4rbL4BGuN+dqZxZvnwPqgqI4jx0Ix/WIpmeFJaHx4d4YR87cZgzwyDMQB7U3m+Hl+VLFdvreZuDFmL/9ocWM7Lulougxl5ru247aPCKhDepJ0NwccqA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
