env:
  global:
    - secure: 1S1uVyyAtlaDbOy3VHGGmZAyiuGjyp+ZDaPBCWHRxO9EpCXWt90HvWVlCw7ErhCGNekd+ia+3ZdEYgtwQde9iiThLwr4HkaWSXl6wId0q3i8Arj15qDkYKEUQXOOVoejIKplE7CmIbUSINq1cGUVcSh9er1ss2NX3344bZIuTzSrolSuStQkdZzXzbIg8A8o5PYSyEoiHkZA9dsLTX8xPfmLyXoYoxiWK25Y3OWb+zIuthiuVbweZzROoSM+UMuauC0/YL8bU+SODYtBMeeILl42CNqUuYzDXiZIQUKvib+r0htOP+6CmynhvsP5d2tV+UgGioy38akf4LVAHcFv1Zx18v3+SSWRSGGsNsqy1vyuLYXsRA097O0cMKPvRLOnO+xcLsWCo6r5ZAhGwbJTO0q4ug6AWELq9fnqH3uLgwUsh69fEkMOcOtD7gFuymDJL6bHO1UqI3PRmvfpFbulJuwBqp62CRUrQSzfn+duC0yL5IXj7nMLOhDeTGC3tIwAjI/D/mdxg/Hfky7pYTOQgkGF7Tv+ixWUvPi10z7Lxcs9nB1cdH/e372CzYB25GTsKYR4oTsuIlucZ66hActI2kTIUxAo27rhywju6uPSa+XMPteGo3e4Lrh9uRL5sui9WSfl9/dcKJ2KJTSRNnCIKF+OGeZTGnId4ADB8UxwelQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
