env:
  global:
    - secure: eYuBBZ9dlzz/ty1YXMFbL0J31M/nMqsmOvy6oAT5FdesZbFTRK87kZUkQLNItBmg3uqrGIVDQabxXEqMudXcC0uaIDnufUCfRj4fkZhVeiSrYdh9ElHULuWmMUpeijGuXz2K9BW8Rxx+tERb/vfeDhi2y+joBwv3oyw45oP7OVadHdwqndrHPWr9nJUQmeHLibfYDOhcMxMYZ2xZdLFn1mEsrCWrZF1mb5tryPOouocmkc7tp0HcCI8VW6RHqyGDInv6cYJJDcdOgYEmkLwFC+xE0dE2lb2XTi2og5c6GgkRF4sEh1xeav0H0OYIujRl3+YEkHTa9zHaUrxvGC0L5WzBlCB0hjBaF4fvooem0COwVWKxoJJcLxePAlO6a3xeqSxAxT+1JTwWZt8dCm2qnklXoJBwlvrNKHdOh7t1NPwAU9TgO6Pc/VBqCOTdbSSPfEFQUIgCE4ULqkk4fJsFyLu0ZwpNw15AvKOFqh2+6hV73sTbAYrTxuiNgM7B7TxXH1fLMC+yzeiKqetZjMPRDJES1ETm108Di2EHbHMRKXJMWrqTGFv60oj/nH5xtjQRyKgR+AjxZkEZlxfKQn7DkcHyPz69rjozqB0s/4wk/xff+954a7hnr2AUYTBu0iZVqFYAZlqhPeXZcK6soCYC8JTbAoTkf4pDbsIVm7Qrj+4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
