env:
  global:
    - secure: gPoTRu6aopp8M59/nFvkmobmhiheh07wr+nYs2gzjeneeW3wh1NNu0fVsw0/Zb1i2CHJ9woxRYFTFKnrW/hmx7sakqUuaq7PusggtMjWVuSwl2odZNzRLuvstueG/o/gD/hNkd9wMjJOGR8eLP5QtOUWuK+4c8HQhnnCpn/BW1Ofq2aT3bgU2DOkBsnKu75qV7aZpZniDf2T8aJA6gNqavr4yVknKuXT3thNdZa1QkdiviAEJXCRdhudj1AwjZR9zPE4fAJveIM4r1t3EbA1k70M9ic6UExPgUabR7BSfTOHbd6TwurAK1Y87il8iMGi6nXUqnvbYrqQ4vCDbvK/UH6251rmdZtC2fC2Mr3KptvWoDJhgB7FMzYDhcroAIbx+aihOt1UbWzZT3CVCtIvDB13wYVImq/rezMBGDt9I7pJLiZCAyqUitrP9eimsTdBwl88E6eYjjRtFD64ad3ADasl6iTyeJDfZ5Xf18d4/WKIbvjo26fG6n6eDnb6+YBaohHj2sW+XNgzq8Tgihv2eKZWsW4FuYZnpJVz+REOn8VfadAw8FGSRWoXIZOZEbpKH0r5jBFibFcBVodK6GwHJi+Pou4cSvmfxJICeIXZI8w0wuVrLa7JZbbo5B8O6h53vUP4UZoqgPcM19AO9AxXutfXP3weKXArcSFBFibVIzM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
