env:
  global:
    - secure: yro/OXCjjAh4LtdWk5sNjNZIsVKjBG8jLtm9JoY/vZNoj80dZCEvtliN4zwF+UJPLKzrWOE1trxlsQHDVyHAj5Dy2qajMsEpMjagQrgMJSNGGFlQxcCkiq8M2XiqRwLShPYMRvC1+0VIp88iLkm+n83y/GV+SysG36RwfA4VaAV7HdoPpKv3tF61XGh4rDMBvSSEsOx0dU95BxznJYbbhIr0S8yLpqID+LFnB67OKmm8z/4ouURZ8hEL7oX4mC9jVpa0z7fF0vnYUuW2jIn0ziIy+43VnYH1EmQGO4AWN+QQDa/dRAwap7z4K+W97/KRm4K0DtW2ARLo7EHhhl8v+MoH/keUOXxesoY0txe+fgqb9Wb3mJ99iixXmZePHwP8gzqSkYR1CQxhAETCGwSjDnKat0hmucE0403yUi11YZWOzzygcYa82zyumBxffADlzEe3U4Q+XUdeCGlhv9/WUvM7DITCjcO6cviXJwoXKdNqqDDdfEykmbGsW+x0FGLRyfSuVCPfXBmUwog/3ZhFo3XKN3ZVdDyxuIG5J6CpyaRJ1ru1Uyt8q6x1wvP5gB8+rDqn7ndz/xSO79hPqqnRxcaozmLwQogikDGd+KQ/MVtMMUhVG/VYU3eIt83z6HXAGZV/Uwx4VgvB1R+wLS3wV9+XL5GT/zcdo0nSYieWbeE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
