env:
  global:
    - secure: gF5LN1RikkvTeS8O4Z1tpLLyC9ZShKdPbKUZFtx6SvEGKUg6DCMtHrHmM8JvcVC9J6Z4bWyrVLa+x04flaoGs4HWindqEmORLX3o4jmlD+yrx8QKDxH+b2mpo+V+inKAN2UnSDykhqlKWWYzJ2hyJQqRWt/XQGhGtJ2/6tZx4rHWKWRdK0aSJBNTkwRLr9ucyhW7Z8XPxONVdwNSfiToRhWInu0WAymqWw5+pk7IggmynPeYC1mLC467ofi918gSHYPtcmIFpwZueK8XaLe0wtA+Ada4BfQNSSiDDKlh7NWaNcpD1GAVtYQZg0WWCVmbFpZsxrcvIBJgk2oZSthPUepgzpSD3sbaPujixns+27sW+MXThCnLq3rrtMdMHzAVEm4ZEWD9SgNuUvKuSy9e5H5Sn1W7okjx6CwMbZ/8s5u2PHccxTxEbdX2Fg9mrv8RChjIhjyMEmop+OUh7Fwar3MAn4uDyv9xFv7KLNcckIDwNEe+WRDnFlu6n6Vhv0ShOWB/7yS+ISZBcbFmAPfBm+aiq3uwqohuk8vbq2puPZeHTzkab7wIKOvSfLtdMtI3xBnoRTepgIavfRV5O8F/a+p3/va8DWqgvvrjrE2sltafMtKJ5HsyE9XFV8+wQYWNK5ACOJw2SVn2D7obhNlzW0QdHzb6GaklSaVmBaQ8/dI=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
