env:
  global:
    - secure: jaryNS2EGLCwPfOtElreiK8URErVoR9Uj+FT6m/ELgb5g79ror1CPYLTvPFVpwJT29+/INkbZCO3mIgb8oJDbj7ss0ekUQNWFe9WzfuOrIs5AxGdeNr/rcF/dII0O9azm/C4nEtwoi1EcYXv3BBVeWlTRokDEfXUK9Skc8c3CU1/ArLSf21ZIqhY5gnU310KnLkCUHEPl5LwEgHUJBBgrE9OiV6k30CXzw6y8o8Qzzta2f0vk1ZMar6oYuGxXFLnjSs7eulOEIccLUtGPgFwWLZaJ8S2ATOqbVOByCBOxfsspdAznYEnckHp3kFOSXbcLFHESG9OuSB8iQJhpKAgmEC+Hzzbgf4d8kBL+ehi0bBp/9Fy4UZ8ci5zih8nkGrWCZ2MxURz2FE9Qe4wEjadPU290LDqlejAMzr4YrCylbNH/UHYqd9R6pUmruNYT3DPXK7o7SUj/vEdjrdk+hWRRmy2Kx8/7mIPQvW7P9GXOq6+koUru/sNx4YAYc3f9srdxYM23dNG8gdLUZlEDJ8/Ws4N89AoEFvZc4ty307RBK/LG7C7kGjRAqIPXIVrI4xfXr3LWd+tsPEI3q+3ZASZ2vniaIaesXtO5ayoipmQef55grrC9w/jr+jwycDCvhGLnOdl3ONzpEQDyG/Um9Y4Secrfm/AfdcgVOkoBBa6kR0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
