env:
  global:
    - secure: s/BD1AIhuXsQ5zsOK2Vts/pg0OVeQZ5RPLXu27je4r1EEA5vxDZuX2boHUHmDc5CAo6UdiSt+xHMJn1ijny48/NhWXltkCDXTef9JKqXYLtszFjzpIZ923u04fnOK/Ctagh1S41XISUIUgfRvsAsyFPCGAL4xkykECuX7zfaFmMCuruv+Ni/ji93Q5oXwQ/M98P949hJui3oiqKqvyU8P1ungRjHHzhjVb+cfE7J6x5k7lg/ZUASUf9Q7FletJvO/dr27ZRDdGYYUEveGX1JeWWDHVFVF9pM6JRBqMXfFrbgLFghDOHJf7SzKkhwtE0PAYlcWdLlLhb9pKK0lRUi0JaROd8rXPiYPDx2xiyzHfknTfn7VxyhFyFe3S2wL+nl6XhpjUsH7C4FyQQuiyxW/Yeu/pHYa2gy9mReg3Hi3U+uu1ZtjSjYL8jwK9ekbtpPvqILSH6SXc6bIjShwK6TLyZXpdmH0SwuWld5bnwhiJZAJr1Zv+rHVBhXzSl74OoPRzumGR1rVFNWf9HmxO5/AThhowmfBW0wAY9ky0sRYHm/ySUysVXwoMbruhM9JfcvFODtp6uDowphbIB5zWb1dEUMQ3y6h7NssaKYSA8uFy9BjaNP1fJE6VUKKwmCc5kGX6SzPGRjcZvIh1dS1tsuNf5FbEq6CV8cRoGW8mBGQJs=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
