env:
  global:
    - secure: WB4vT7PqzJwF9kaoxK0q/J16wmSfvXXo1wwiSQ6Qd4IoVT6nb5eDXoMIJdYO9+Aq9ASRtlgnlqtuWS1pN8tumGyKpLUBQE7Sb00GBYuEmlJ4nWDE/EMO23Hf+Pi3v268Veok9g0QMLG5kDxaJKG9GtjXPTTsDKdsTaLgT8w+6NHk+gzhRxbxH913b2KWZAX4PUBIiu/Cp0T1V0VRUG9EADdFxbIrPMBhzqfSGzUh5Veqqw0kA8KU4PLMfuMO0xajYDzA6XDH39il1lLntZMZAhX9Ia8LJqBnAoFUOksgxQ9H9m98ibF4smiVYN8iwWuQXV79fQURatS6JUPYhtoECwHGq4WF5ptmjSOYkNAg4BM50bQyRtpQK+p7ajWHBlVhgsorJdTV20WLjx2E7FrAcb72GwqsqyV6NSSj0egvEevZ7WBsm97JcWNjDsYyqHXD5BV4ib2uwZh57BNn+2V83dQI0YqoqrLT0gjtXdd5L9Y+O5uH1MxtgmLe4uUrg5wsLyvRyKpNdTn4rsOZ0/OEt++LNdeZAyPXAgnAC27cIHOZ6LvWbNzAsmlIbdHZ0WON+ZL5dXHx8JjATdNTZqcAZ0Bzg4Yb/C41JpqQYq2cZRMggkaT6NAZc9JQ4VpBVZSXZyM3r1QfSE+YgZlKnutlm4MpmSGOMHpJExJ64we5F1Y=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/cookies_filters_git_MajkiIT
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

before_script:
  - if [[ ! -f .administrators ]]; then wget "${UPDATE_ME_LOCATION}" -o /dev/null -O update_me.py && chmod +x update_me.py; else echo "update_me not downloaded :)"; fi
  - if [[ ! -f .administrators ]]; then wget "${ADMIN_LOCATION}" -o /dev/null -O admin.py && chmod +x admin.py; else echo "admin not downloaded :)"; fi

script:
  - python3 update_me.py

notifications:
  on_success: change
  on_failure: always
